# host env init before deploy k8s
- hosts: all
  become: yes
  gather_facts: no
  vars:
    registry_host: 10.57.30.78
    reposite_host: 10.57.30.78
  tasks:
  - name: clear registry hosts
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: 'registry1'

  - name: set registry hosts
    lineinfile:
      path: /etc/hosts
      line: "{{registry_host}} registry1"

  - name: clear reposite hosts
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: 'reposite1'

  - name: set reposite hosts
    lineinfile:
      path: /etc/hosts
      line: "{{reposite_host}} reposite1"

  - name: swap off
    command: swapoff -a

  - name: disable SELinux
    command: setenforce 0
    register: verification
    changed_when: verification.rc == 1
    failed_when: verification.rc not in [0,1]

  - name: disable SELinux on reboot
    selinux:
      state: disabled

  - name: flush iptables
    raw: iptables -F > .iptables_flushed
    args:
      chdir: $HOME
      creates: .iptables_flushed

  - name: disalbe firewall
    service:
      name: firewalld
      enabled: no
      state: stopped
    ignore_errors: yes

  - name: insmod br_netfilter
    command: modprobe br_netfilter

  - name: ensure net.ipv4.ip_forward is set to 1
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present

  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
